//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace egeszsegismProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FeladatFajtaListaTabla> FeladatFajtaListaTabla { get; set; }
        public virtual DbSet<FeladatTabla> FeladatTabla { get; set; }
        public virtual DbSet<FeladatTipusTabla> FeladatTipusTabla { get; set; }
        public virtual DbSet<TemakorFeladatKapcsolo> TemakorFeladatKapcsolo { get; set; }
        public virtual DbSet<TemaTabla> TemaTabla { get; set; }
        public virtual DbSet<TemakorListaTabla> TemakorListaTabla { get; set; }
        public virtual DbSet<FeladatMoTabla> FeladatMoTabla { get; set; }
    }
}
