//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace egeszsegismProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemakorFeladatKapcsolo
    {
        public int Id { get; set; }
        public Nullable<int> FeladatFK { get; set; }
        public Nullable<int> TemaFK { get; set; }
    
        public virtual FeladatTabla FeladatTabla { get; set; }
        public virtual TemaTabla TemaTabla { get; set; }
    }
}
