//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace egeszsegismv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeladatMoTabla
    {
        public int Id { get; set; }
        public string FeladatMoPdf { get; set; }
        public Nullable<decimal> Szelesseg { get; set; }
        public Nullable<decimal> Magassag { get; set; }
        public byte[] Kep { get; set; }
    
        public virtual FeladatTabla FeladatTabla { get; set; }
    }
}
